#!/bin/bash

output_file_name="/tmp/fetched-qr.png"

function cleanup-image() {
    [ -f "$output_file_name" ] && rm "$output_file_name"
}

# take a screenshot and extract the url
flameshot gui --path "$output_file_name"
url=$(zbarimg -q "$output_file_name" | sed 's/QR-Code://')
if [ "$url" == "" ]; then
    notify-send "url is required, make sure the qr is valid!"
    cleanup-image
    exit 1
fi

# ask the user for password name
name="$(dmenu -p "Enter Password Name: " </dev/null)"
if [ "$name" == "" ]; then
    notify-send "password name is required!"
    cleanup-image
    exit 1
fi

# add the password to pass
pass otp insert "$name" <<<"$url"
notify-send "added $name to passwords"
cleanup-image
