#!/bin/bash

bookmarks_file="$JOURNAL_DIR/bookmarks.txt"
[ ! -f "$bookmarks_file" ] && touch "$bookmarks_file"

focused_window_id=$(xdotool getwindowfocus)
window_title=$(xprop -id "$focused_window_id" | awk -F '"' '/^WM_NAME/{$2=$2; print $2}')
window_class=$(xprop -id "$focused_window_id" | grep "WM_CLASS" | awk '{print $4}')

is_browser=false
grep -iE "brave-browser|firefox|chromium" <<<"$window_class" && is_browser=true

[ $is_browser ] && {
    xdotool key --clearmodifiers ctrl+l key ctrl+c key Escape
    url=$(xclip -sel clipboard -o)
    [ -n "$url" ] && {
        echo "- [$window_title]($url)" >>"$bookmarks_file" && notify-send -r 123455 -t 800 "Bookmarks" "$window_title\n\n$url"
        echo "$url" | xclip -selection clipboard
        echo "$url" | xclip -selection primary
    }
}
