#!/bin/bash

if [ "$OSTYPE" == "linux-gnu" ]; then
    command -v firefox >/dev/null && firefox "$@" && exit
    command -v chromium >/dev/null && chromium "$@" && exit
    command -v brave >/dev/null && brave "$@" && exit
    echo "no browser found" && exit
fi
