#!/bin/bash
# I need to learn xclip xdotool ... (maybe at my job)

bookmarkFile="/media/projects/logs/bookmarks.md"

[ -f $bookmarkFile ] && true || notify-send -i $bookmarkIcon "Bookmarks" "file not found"
cat $bookmarkFile | dmenu -i -l 15 -vi | xclip -selection -clipboard
selection=$(xclip -o)
result=$(echo "$selection" | awk -F'[()]' '{print $(NF-1)}')
notify-send "$result"
echo "$result" | xclip -selection clipboard
echo "$result" | xclip -selection primary
# open only if some bookmark is selected
[ -n "$selection" ] && browser $result
