#!/bin/bash

clipboard=$(xclip -o -selection clipboard)

if [ -n "$clipboard" ]; then
    notify-send "uploading from clipboard" "$clipboard"
    url=$(echo "$clipboard" | nc termbin.com 9999)

    notify-send "paste url" "$url"
    echo "$url" | xclip -selection clipboard
    echo "$url" | xclip -selection primary
else
    notify-send "clipboard empty"
fi
